### PR TITLE
change scrollbar css according to theme

### LINKED ISSUE #38: Scrollbar dark/light mode
Scrollbar should have background color according to selected theme

image

### PR DESCRIPTION
**Pull request by Ritesh-Aggarwal**
closes #38 

image

image

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]
Looking good 🚀 
Could you also add support for the custom scrollbar theme for firefox?

**Review by developedBySJ — APPROVED** [review]

**Comment by Ritesh-Aggarwal** [comment]
> Looking good 🚀 Could you also add support for the custom scrollbar theme for firefox?

Thanks for pointing that out , will fix it for firefox too

**Comment by Ritesh-Aggarwal** [comment]
Doesn't firefox default scrollbar look better? 

image
image

**Comment by rithviknishad** [comment]
Yup. I just thought to have a consistent experience regardless of the browser.

**Comment by developedBySJ** [comment]
@rithviknishad Let's keep it default for firefox.

**Pull request merged**
